Add delocalised coordinates parsers
oerc0122/castep_outputs pull request #153
Opened 2024-07-31 13:00 UTC by oerc0122

Fixes #111

2025-01-17 16:16 UTC, ajjackson commented on castep_outputs/parsers/castep_file_parser.py
> +        actual = float(actual)
Some fun stuff is happening here but without input examples it's hard to understand how these variable names relate to something that can be two floats, or a string and float in the other order.

2025-01-17 16:16 UTC, ajjackson commented on castep_outputs/parsers/castep_file_parser.py
> +        assert type_ in ("Bond", "Angle", "Torsion")
Should this assert be above `if actual == "Satisfied":` (i.e. directly below `type_` is assigned)?

2025-01-19 15:10 UTC, oerc0122 commented on castep_outputs/parsers/castep_file_parser.py
> +        actual = float(actual)
So this is due to weird and awkward formatting coming out of CASTEP, I don't understand it either.

Rough translation to Python:
```python
#19) vali (in) : current value of the constrained internal
#20) rc (in) : prescribed value of the constrained internal

# Unsatisfied
print(f"{index:d3} Bond  {rc:f9.3}{vali:f10.3} ... # Constraints listing")

#Satisfied
print(f"{index:d3} Bond  {vali:f9.3} Satisfied ... # Constraints listing")
```
So it swaps when satisfied for some reason. I will try to work out a better expression of it.

2025-01-20 09:43 UTC, ajjackson commented on castep_outputs/parsers/castep_file_parser.py
> +        actual = float(actual)
Maybe this is a case where trying two different regex would be clearer than splitting to (potentially incorrect) variable names?

2025-01-20 11:14 UTC, oerc0122 commented on castep_outputs/parsers/castep_file_parser.py
> +        actual = float(actual)
At the moment, I thankfully avoid any regex, I think probably a comment would be more clear. Having a think.

2025-01-20 11:24 UTC, ajjackson commented on castep_outputs/parsers/castep_file_parser.py
> +        actual = float(actual)
Perhaps the real problem here is stuffing "Satisfied" into "target" when it is a difference piece of information from the target value.

2025-01-20 11:25 UTC, oerc0122 commented on castep_outputs/parsers/castep_file_parser.py
> +        actual = float(actual)
I did consider renaming it "actual_or_sat", but I felt that added less clarity. I have renamed it to "current" rather than "actual" and added a (hopefully) clarifying comment.

2025-01-20 11:26 UTC, ajjackson commented on castep_outputs/parsers/castep_file_parser.py
> +            target, current = float(target), float(current)
This works for me. The remaining ugliness reflects the underlying behaviour 😅

2025-01-20 11:29 UTC, ajjackson commented on castep_outputs/parsers/castep_file_parser.py
> +        actual = float(actual)
An alternative approach would be to add a separate "satisfied" boolean to the data object, and set target to `None` for these blocks.

This will make it clearer to a downstream parser what is going on, and we don't have to worry any more about people doing number things to a string. (They might do them to None, but at least a noisy error is more likely.)

2025-01-20 11:35 UTC, oerc0122 commented on castep_outputs/parsers/castep_file_parser.py
> +        actual = float(actual)
That is a very good idea, going to do that. 

How's this for a brain-bender then?
```python
if type == "bond":
    print(f"{j:d3} Bond   {rc:f9.*3*}{vali:10.*3*} ...")
elif type == "torsion":
   print(f"{j:d3} Torsion{rc:f9.*2*}{vali:10.*2*} ...")
```
"angle" constraints are similar to "torsion" ones.
I'm glad I'm not doing exact REs (though I "should" since there's strictly no spacing for very large values, but if you've got a million angstrom long constraint you have other problems)

2025-01-20 11:47 UTC, ajjackson commented on castep_outputs/parsers/castep_file_parser.py
> +        actual = float(actual)
I guess bonds just have to be a _bit_ more precise!

How did so many academic Fortran developers learn to never leave spaces between number fields?

2025-01-20 12:00 UTC, ajjackson requested changes
A couple of issue with the schema.

Which presumably means it isn't being tested anywhere? But it is hard to validate a TypedDict except by running mypy. Maybe this beartype feature would help, I've never tried it: https://beartype.readthedocs.io/en/latest/faq/#how-do-i-only-type-check-while-running-my-test-suite

(The requested change is to update the schema, not to add more CI.)

2025-01-20 12:00 UTC, ajjackson commented on castep_outputs/utilities/datatypes.py
> +    target: Literal["Satisfied"] | float
I think this now needs splitting to separate fields to match the code above?

2025-01-20 12:00 UTC, ajjackson commented on castep_outputs/utilities/datatypes.py
> +    num_inversions: int
Should this be "num_internals?"

2025-01-20 14:05 UTC, oerc0122 commented
> A couple of issue with the schema.
> 
> Which presumably means it isn't being tested anywhere? But it is hard to validate a TypedDict except by running mypy. Maybe this beartype feature would help, I've never tried it: https://beartype.readthedocs.io/en/latest/faq/#how-do-i-only-type-check-while-running-my-test-suite
> 
> (The requested change is to update the schema, not to add more CI.)

You are correct, and highlighted the fact that I'd broken my `flycheck` configuration and it wasn't running `mypy` (my hacked together `flycheck-ruff` accidentally prevented any other flycheck running on Python). There are quite a few `mypy` errors, so I think I'll fix those as a separate PR, if you're happy I've fixed these for now. 

Eventually, I suspect I'll add `mypy` (or similar) to the CI.

2025-01-20 14:20 UTC, ajjackson approved these changes

2025-01-20 14:22 UTC, merged