Change md/geom parsing to frame function for easier use.
oerc0122/castep_outputs pull request #176
Opened 2024-11-28 11:57 UTC by oerc0122

- Fix issue with reading all frames of MD/Geom files
- Add a function to parse a single frame of an MD calculation from a block enabling generator approaches.

2024-12-04 16:55 UTC, ajjackson commented on castep_outputs/parsers/md_geom_file_parser.py
>          elif match := ATDATTAG.match(line):
Is this "AT_DAT_TAG"? Took a while to parse...

2024-12-04 16:55 UTC, ajjackson commented on castep_outputs/parsers/md_geom_file_parser.py
> +    if curr and curr["ions"]:
It looks to me like `curr` always contains "ions" here and so is always Truth-y?
Indeed, `curr["ions"]` is guaranteed to be a dict so it should always be safe to iterate over `.values()`; maybe this `if` statement can be removed.

2024-12-04 17:01 UTC, oerc0122 commented on castep_outputs/parsers/md_geom_file_parser.py
>          elif match := ATDATTAG.match(line):
It is `ATomicDATaTAG`, yeah. from a time before naming.

2024-12-04 17:04 UTC, oerc0122 commented on castep_outputs/parsers/md_geom_file_parser.py
> +    if curr and curr["ions"]:
I think the `return curr` used to be in the block and has been shuffled in some refactor or other. I'll take a look and have a think.

2024-12-05 09:33 UTC, ajjackson reviewed
A couple of tidy-up/clarity suggestions but nothing too critical.

2024-12-05 09:33 UTC, ajjackson commented on castep_outputs/parsers/md_geom_file_parser.py
> +
Would it be useful to pack `bool(str(block).strip())` into a `.__bool__()` method on Block so that "False-y" Blocks can be checked directly?

2024-12-05 09:33 UTC, ajjackson commented on castep_outputs/parsers/md_geom_file_parser.py
>          elif match := ATDATTAG.match(line):
Is that an established abbreviation from CASTEP source, or a new one for this repo?

2024-12-05 11:32 UTC, oerc0122 commented on castep_outputs/parsers/md_geom_file_parser.py
>          elif match := ATDATTAG.match(line):
No, a nightmare dredged up while in seas of RegEx. I will fix it.

2024-12-05 11:36 UTC, oerc0122 commented on castep_outputs/parsers/md_geom_file_parser.py
> +
`bool(block) == bool(block._data)` so if there's an empty string in there it still counts. Maybe a `has_text` method.

2024-12-05 11:53 UTC, ajjackson commented on castep_outputs/parsers/md_geom_file_parser.py
> +
Is the current behaviour useful or could we define all whitespace-only blocks as false-y?

2024-12-05 13:42 UTC, oerc0122 commented on castep_outputs/parsers/md_geom_file_parser.py
> +
That would be a possibility.

2024-12-05 14:08 UTC, oerc0122 commented on castep_outputs/parsers/md_geom_file_parser.py
>          elif match := ATDATTAG.match(line):
Moved to #180, #181

2024-12-05 16:02 UTC, ajjackson commented
I think `if curr and curr["ions"]` is the only thing left, now

2025-01-10 11:05 UTC, ajjackson requested changes
```
castep_outputs/utilities/dumpers.py:53:5: D403 [*] First word of the docstring should be capitalized: `yaml` -> `Yaml`
   |
52 |   def yaml_dumper(data: Any, file: TextIO):
53 |       """
   |  _____^
54 | |     yaml format dumper.
55 | | 
56 | |     Parameters
57 | |     ----------
58 | |     data
59 | |         Data to dump.
60 | |     file
61 | |         File to dump to.
62 | |     """
   | |_______^ D403
63 |       yaml.dump(data, file)
   |
   = help: Capitalize `yaml` to `Yaml`

Found 1 error.
[*] 1 fixable with the `--fix` option.
```

Not ruff's finest moment 😞 . I guess we actually want `YAML format dumper.`

The full stop is also grammatically dubious (yet required).

2025-01-10 13:41 UTC, ajjackson approved these changes

2025-01-10 13:42 UTC, merged